using System.Numerics;

namespace Zinc.Sandbox.Demos;

// Custom-shader demo using the material system: a fullscreen Shape whose .Shader is set to the SDF
// pipeline compiled from res/shaders/sdf.glsl. Uniforms are set by filling the generated std140
// record-struct (Res.Shaders.sdf.Fs) and handing it to .Material.SetFragmentUniforms — the whole
// block is uploaded at draw via sgp_set_uniform (sokol's sg_apply_uniforms model). The .Shader /
// .Material accessors are generated by Zinc.ECSGenerator from MaterialComponent's [EntityAccessible] members.
[DemoScene("SGP_Example_SDF")]
public class SGP_Example_SDF : Scene
{
    public override void Create()
    {
        // color white so the shader's `* iColor` (vertex color) doesn't tint the result
        var rect = new Shape(Engine.Width, Engine.Height, color: new Color(1f, 1f, 1f, 1f));
        rect.Shader = Res.Assets.sdf;
        rect.Renderer_Pivot = Vector2.Zero; // anchor top-left so the rect covers (0,0)-(W,H)

        rect.Update = (self, dt) =>
        {
            var s = (Shape)self;
            s.Renderer_Width = Engine.Width;   // keep it fullscreen across resizes
            s.Renderer_Height = Engine.Height;
            s.Material.SetFragmentUniforms(new Res.Shaders.sdf.Fs
            {
                iResolution = new Vector2(Engine.Width, Engine.Height),
                iTime = (float)Engine.Time,
            });
        };
    }
}
